version: '3'
services:
  rails:
    build:
      context: ./src
      # dockerfile: Dockerfile
    volumes:
      - ./src:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      RAILS_DATABASE_HOST: db
      RAILS_DATABASE_USER: pguser
      RAILS_DATABASE_PASSWORD: password
      MAIL_HOST: mail
    env_file: .env
  db:
    image: shojik/postgres:12
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
  # front:
  #   image: node:12
  #   tty: true
  #   # command: bash -c "yarn install"
  #   # command: bash -c "yarn install && yarn start"
  #   volumes:
  #     - ./src/frontend:/app
  #   ports:
  #     - 8080:8080
  #     - 8081:9009
  #   environment:
  #     VUE_APP_API_URL: http://dev.freks.jp:33000
  #   working_dir: /app
  # mail:
  #   image: schickling/mailcatcher
  #   ports:
  #     - "33001:1080"
volumes:
  bundle:
