default: &default
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('RAILS_DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('RAILS_DATABASE_USER', 'pguser') %>
  password: <%= ENV.fetch('RAILS_DATABASE_PASSWORD', 'password') %>

development:
  <<: *default
  database: sampledb

test:
  <<: *default
  database: sampledb_test

production:
  <<: *default
  database: sampledb_production
