require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "frontend/*"
  DisplayCopNames: true

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - "spec/**/*_spec.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/Present:
  Exclude:
    - 'bin/bundle'

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "Gemfile"
    - "Guardfile"
    - "config/environments/*.rb"
    - "config/routes.rb"
    - "config/routes/**/*.rb"
    - "*.gemspec"

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Metrics/PerceivedComplexity:
  Max: 9

Layout/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"
    - "db/fixtures/development/*.rb"
    - "db/fixtures/production/*.rb"
